Problem Statement : Hospital Patient Data Analysis
Context:
A hospital maintains patient records including admission details, department, diagnosis, doctor, and bill amount. You have two datasets: one with patient info and another with billing details. Some patients have blank bill amounts, and there are multiple rows for the same patient due to follow-ups.
Tasks:
1.Load the patient dataset and show summary with info().
2.Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].
billing_df = patient_df[['PatientID','Department','Doctor','BillAmount']]
billing_df.head() ['ReceptionistID', 'CheckInTime'].
4.Use groupby to find total bill amount per department.
5.Remove duplicate patient records based on PatientID.
6.Fill missing BillAmount values with the mean bill amount.
7.Merge the billing dataset with patient dataset on PatientID.
8.Concatenate an additional DataFrame that contains new patients for the current week (row-wise).
9.Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).
Expected Outcome:
Final cleaned dataset with accurate billing info.
All missing values handled, merged dataset across PatientID.
Ability to perform further analytics on department-wise revenue or doctor performance.

PROBLEM STATEMENT : HOSPITAL PATIENT DATA ANALYSIS

A hospital maintains patient records including admission details, department, diagnosis, doctor, and bill amount. You have two datasets: one with patient info and another with billing details. Some patients have blank bill amounts, and there are multiple rows for the same patient due to follow-ups.

1.Load the patient dataset and show summary with info().

In [12]:
import pandas as pd
patient_df = pd.read_csv("Patient_Data.csv")
patient_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

2.Select only the columns relevant for billing:

In [13]:
billing_df = patient_df[['PatientID','Department','Doctor','BillAmount']]
billing_df.head()

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN

3.Drop administrative columns like ['ReceptionistID', 'CheckInTime'].

In [14]:
patient_df = patient_df.drop(columns=['ReceptionistID','CheckInTime'])
patient_df.head()

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

4.Use groupby to find total bill amount per department.

In [15]:
department_bill = patient_df.groupby('Department')['BillAmount'].sum()
department_bill

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

5.Remove duplicate patient records based on PatientID.

In [16]:
patient_df = patient_df.drop_duplicates(subset='PatientID')
patient_df.head()

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

6.Fill missing BillAmount values with the mean bill amount.

In [17]:
patient_df['BillAmount'] = patient_df['BillAmount'].fillna(patient_df['BillAmount'].mean())
patient_df.head()

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

7.Merge the billing dataset with patient dataset on PatientID.

In [18]:
billing_data = pd.read_csv("Billing_Data.csv")
merged_df = pd.merge(patient_df, billing_data, on='PatientID')
merged_df.head()

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

8.Concatenate an additional DataFrame that contains new patients for the current week (row-wise).

In [19]:
new_patients = pd.DataFrame({
    'PatientID':[106,107],
    'Name':['Riya','Karan'],
    'Department':['Cardiology','Neurology'],
    'Doctor':['Dr. Mehta','Dr. Singh'],
    'BillAmount':[4500,5200]
})
final_df = pd.concat([merged_df,new_patients],ignore_index=True)
final_df.head()

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000.0,3000.0
1,102,Bob,Neurology,Dr. John,6233.333333,1500.0,3500.0
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500.0,5000.0
3,104,David,Cardiology,Dr. Smith,6200.000000,3000.0,3200.0
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000.0,4000.0

9.Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

In [20]:
extra_columns = pd.DataFrame({
    'InsuranceCovered':[1000]*len(final_df),
    'FinalAmount':final_df['BillAmount'].fillna(0)-1000
})

final_df = pd.concat([final_df,extra_columns],axis=1)
final_df.head()

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000.0,3000.0,1000,4000.000000
1,102,Bob,Neurology,Dr. John,6233.333333,1500.0,3500.0,1000,5233.333333
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500.0,5000.0,1000,6500.000000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000.0,3200.0,1000,5200.000000
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000.0,4000.0,1000,5233.333333

Expected Outcome:
Final cleaned dataset with accurate billing info.
All missing values handled, merged dataset across PatientID.
Ability to perform further analytics on department-wise revenue or doctor performance.

CONCLUSION:
The patient dataset was successfully cleaned by removing duplicate records, filling missing bill amounts, and dropping unnecessary columns. The patient and billing datasets were merged on PatientID, and additional rows and columns were concatenated successfully. The final dataset is clean and ready for further analysis such as department-wise revenue and doctor performance.